name: Go

on:
  workflow_dispatch:
    branches: [main]
  schedule:
    - cron: "0 23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v -o Todo . && ./Todo ${{secrets.HDU_USERNAME}} ${{secrets.HDU_PASSWORD}}

<<<<<<< HEAD
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: fanya todo notification
          body: file://./page/email.html
          to: ${{secrets.MAIL_ADDRESS}}
          from: nic
          content_type: text/html
=======
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: fanya todo notification
        body: file://./page/email.html
        to: ${{secrets.MAIL_ADDRESS}}
        from: nic
        content_type: text/html
>>>>>>> upstream/main
